version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
      # - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Generate Allure report
          command: npm run report-ci
          when: always
      - store_artifacts:
          name: Upload Allure report
          path: allure-report