version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest
      - image: selenium/standalone-chrome:latest
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test