version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run report-ci
      - store_artifacts:
          path: allure-report