version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: allure generate allure-results -o allure-report
      - store_artifacts:
          path: allure-report