version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: selenium/standalone-chrome:latest
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test